#!/bin/sh

cd $(dirname $0)

for calfile in ./*.cal examples/*.cal; do
    echo "Running with cal file : $calfile" >> result
    ./bddcalc $calfile | egrep -v '^Garbage collection' >> result
done

if cmp -s expected result; then rm result; else exit $?; fi
