#!/bin/sh

cd $(dirname $0)

for N in 4 8 9 10; do
    echo "Running with N = $N" >> result
    ./queen $N | egrep -v '^Garbage collection' >> result
done

if cmp -s expected result; then rm result; else exit $?; fi
